---
galaxy_info:
  author: Tim Goodwin (portfolio demo)
  description: Installs Dynatrace OneAgent with EasyTrade-specific properties
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions: ["8", "9"]
    - name: Ubuntu
      versions: ["20.04", "22.04"]
dependencies: []